### ISSUE TITLE
Using node-blue with express

### ISSUE THREAD

**Issue by Indiepath** [Floby/node-blue#1]
Apologies as this is not an issue with your code, it's more of an issue with a new nodejs user wanting to use your excellent template module with express.

Can you help?

Thanks

Tim.

**Comment by Floby** [comment]
Glad to see someone working with Blue.
Yeah, last time I checked Express expected template engines to _return_ a string. This is not quite possible with blue as it would lose all interest.
If you don't use it especially for streams and async includes, you're better off using [ejs](https://github.com/visionmedia/ejs).

**Comment by Indiepath** [comment]
That's a shame - thanks for the advice on ejs. Perhaps when I have a little more experience I'll figure out how to make it all hang together.
